#
# baseado em https://tobiasmaier.info/posts/2018/03/13/hosting-helm-repo-on-gitlab-pages.html
#
lint:
  image:
    name: alpine/helm:3.1.1
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm lint vkpr/

pages:
  image:
    name: alpine/helm:3.1.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - helm dependency update vkpr/
    - mkdir -p ./public
    - "echo \"User-Agent: *\" > ./public/robots.txt"
    - "echo \"Disallow: /\" >> ./public/robots.txt"
    - helm package vkpr/ --destination ./public
    - helm repo index --url https://vertigobr.gitlab.io/vkpr/${CI_PROJECT_NAME} ./public
    - cat ./public/index.yaml
  artifacts:
    paths:
      - public
  only:
    - master
